from sqlalchemy.orm import Session
from sqlalchemy.exc import SQLAlchemyError, IntegrityError

from tuned.extensions import db
from tuned.models import Sample
from tuned.dtos.content import SampleDTO, SampleResponseDTO
from tuned.repository.exceptions import AlreadyExists, DatabaseError, NotFound


class CreateSample:
    def __init__(self, db: Session) -> None:
        self.db = db

    def execute(self, data: SampleDTO) -> SampleResponseDTO:
        try:
            # slug is auto-generated by Sample.__init__ if not provided
            sample = Sample(
                title=data.title,
                content=data.content,
                service_id=data.service_id,
                excerpt=data.excerpt,
                word_count=data.word_count,
                featured=data.featured,
                image=data.image,
                slug=data.slug or None,
            )
            self.db.session.add(sample)
            self.db.session.commit()
            return SampleResponseDTO.from_model(sample)
        except IntegrityError:
            self.db.session.rollback()
            raise AlreadyExists("A sample with this title or slug already exists.")
        except SQLAlchemyError as e:
            self.db.session.rollback()
            raise DatabaseError("Database error while creating sample.") from e


class GetSampleByID:
    def __init__(self, db: Session) -> None:
        self.db = db

    def execute(self, sample_id: str) -> SampleResponseDTO:
        try:
            sample = self.db.session.query(Sample).filter_by(id=sample_id).first()
            if not sample:
                raise NotFound("Sample not found.")
            return SampleResponseDTO.from_model(sample)
        except SQLAlchemyError as e:
            raise DatabaseError(f"Database error while fetching sample: {str(e)}") from e


class GetSampleBySlug:
    def __init__(self, db: Session) -> None:
        self.db = db

    def execute(self, slug: str) -> SampleResponseDTO:
        try:
            sample = self.db.session.query(Sample).filter_by(slug=slug).first()
            if not sample:
                raise NotFound("Sample not found.")
            return SampleResponseDTO.from_model(sample)
        except SQLAlchemyError as e:
            raise DatabaseError(f"Database error while fetching sample: {str(e)}") from e


class GetAllSamples:
    def __init__(self, db: Session) -> None:
        self.db = db

    def execute(self, service_id: str | None = None, featured_only: bool = False) -> list[SampleResponseDTO]:
        try:
            query = self.db.session.query(Sample)
            if service_id:
                query = query.filter_by(service_id=service_id)
            if featured_only:
                query = query.filter_by(featured=True)
            samples = query.order_by(Sample.created_at.desc()).all()
            return [SampleResponseDTO.from_model(s) for s in samples]
        except SQLAlchemyError as e:
            raise DatabaseError(f"Database error while fetching samples: {str(e)}") from e


class UpdateSample:
    def __init__(self, db: Session) -> None:
        self.db = db

    def execute(self, sample_id: str, updates: dict) -> SampleResponseDTO:
        try:
            sample = self.db.session.query(Sample).filter_by(id=sample_id).first()
            if not sample:
                raise NotFound("Sample not found.")
            for key, value in updates.items():
                if hasattr(sample, key):
                    setattr(sample, key, value)
            self.db.session.commit()
            return SampleResponseDTO.from_model(sample)
        except IntegrityError:
            self.db.session.rollback()
            raise AlreadyExists("A sample with that title or slug already exists.")
        except SQLAlchemyError as e:
            self.db.session.rollback()
            raise DatabaseError("Database error while updating sample.") from e


class DeleteSample:
    def __init__(self, db: Session) -> None:
        self.db = db

    def execute(self, sample_id: str) -> None:
        try:
            sample = self.db.session.query(Sample).filter_by(id=sample_id).first()
            if not sample:
                raise NotFound("Sample not found.")
            self.db.session.delete(sample)
            self.db.session.commit()
        except SQLAlchemyError as e:
            self.db.session.rollback()
            raise DatabaseError("Database error while deleting sample.") from e


class SampleRepository:
    """Facade composing all Sample command objects."""

    def __init__(self) -> None:
        self.db = db

    def create(self, data: SampleDTO) -> SampleResponseDTO:
        return CreateSample(self.db).execute(data)

    def get_by_id(self, sample_id: str) -> SampleResponseDTO:
        return GetSampleByID(self.db).execute(sample_id)

    def get_by_slug(self, slug: str) -> SampleResponseDTO:
        return GetSampleBySlug(self.db).execute(slug)

    def get_all(
        self,
        service_id: str | None = None,
        featured_only: bool = False,
    ) -> list[SampleResponseDTO]:
        return GetAllSamples(self.db).execute(service_id, featured_only)

    def update(self, sample_id: str, updates: dict) -> SampleResponseDTO:
        return UpdateSample(self.db).execute(sample_id, updates)

    def delete(self, sample_id: str) -> None:
        return DeleteSample(self.db).execute(sample_id)