[mypy]
python_version = 3.14
strict = True

ignore_missing_imports = True

warn_unused_ignores = True
warn_return_any = True
disallow_untyped_defs = True
exclude = (^|/)temp/|(^|/)tests/|(^|/)migrations/|.*1\.py$