from typing import Protocol, Sequence, TYPE_CHECKING, runtime_checkable

if TYPE_CHECKING:
    from tuned.dtos import (
        ActivityLogCreateDTO, ActivityLogResponseDTO, ActivityLogFilterDTO,
        EmailLogCreateDTO, EmailLogResponseDTO, EmailLogFilterDTO, EmailLogUpdateDTO,
        OrderStatusHistoryCreateDTO, OrderStatusHistoryResponseDTO,
        PriceHistoryCreateDTO, PriceHistoryResponseDTO
    )

@runtime_checkable
class ActivityLogRepositoryProtocol(Protocol):
    def create(self, data: "ActivityLogCreateDTO") -> "ActivityLogResponseDTO": ...
    def get_by_id(self, log_id: str) -> "ActivityLogResponseDTO": ...
    def get_filtered(self, filters: "ActivityLogFilterDTO") -> tuple[Sequence["ActivityLogResponseDTO"], int]: ...

@runtime_checkable
class EmailLogRepositoryProtocol(Protocol):
    def create(self, data: "EmailLogCreateDTO") -> "EmailLogResponseDTO": ...
    def get_by_id(self, log_id: str) -> "EmailLogResponseDTO": ...
    def get_filtered(self, filters: "EmailLogFilterDTO") -> tuple[Sequence["EmailLogResponseDTO"], int]: ...
    def update_status(self, log_id: str, data: "EmailLogUpdateDTO") -> "EmailLogResponseDTO": ...

@runtime_checkable
class OrderStatusHistoryRepositoryProtocol(Protocol):
    def create(self, data: "OrderStatusHistoryCreateDTO") -> "OrderStatusHistoryResponseDTO": ...
    def get_by_id(self, history_id: str) -> "OrderStatusHistoryResponseDTO": ...
    def get_by_order(self, order_id: str, page: int = 1, per_page: int = 20) -> tuple[Sequence["OrderStatusHistoryResponseDTO"], int]: ...

@runtime_checkable
class PriceHistoryRepositoryProtocol(Protocol):
    def create(self, data: "PriceHistoryCreateDTO") -> "PriceHistoryResponseDTO": ...
    def get_by_id(self, history_id: str) -> "PriceHistoryResponseDTO": ...
    def get_by_rate(self, rate_id: str, page: int = 1, per_page: int = 20) -> tuple[Sequence["PriceHistoryResponseDTO"], int]: ...
