from typing import Protocol, Sequence, TYPE_CHECKING, runtime_checkable

if TYPE_CHECKING:
    from tuned.dtos import (
        BlogCategoryDTO, BlogCommentDTO, BlogPostDTO, CommentReactionDTO,
        BlogPostListRequestDTO, PostByCategoryRequestDTO,
        BlogPostListResponseDTO
    )
    from tuned.models.blog import BlogPost, BlogComment, BlogCategory, CommentReaction

@runtime_checkable
class BlogRepositoryProtocol(Protocol):
    # Blog posts
    def create_blog(self, data: "BlogPostDTO") -> "BlogPost": ...
    def get_blog_post_by_slug(self, slug: str) -> "BlogPost": ...
    def get_blog_post_by_id(self, id: str) -> "BlogPost": ...
    def get_featured(self) -> Sequence["BlogPost"]: ...
    def get_published(self, req: "BlogPostListRequestDTO") -> "BlogPostListResponseDTO": ...
    def update_or_delete_post(self, id: str, data: "BlogPostDTO") -> "BlogPost": ...
    def get_by_category(self, req: "PostByCategoryRequestDTO") -> Sequence["BlogPost"]: ...

    # Blog categories
    def create_blog_category(self, data: "BlogCategoryDTO") -> "BlogCategory": ...
    def get_blog_category_by_slug(self, slug: str) -> "BlogCategory": ...
    def list_blog_categories(self) -> Sequence["BlogCategory"]: ...
    def update_or_delete_category(self, id: str, data: "BlogCategoryDTO") -> "BlogCategory": ...

    # Blog comments
    def create_blog_comment(self, data: "BlogCommentDTO") -> "BlogComment": ...
    def get_blog_comment(self, id: str) -> "BlogComment": ...
    def update_or_delete_comment(self, id: str, data: "BlogCommentDTO") -> "BlogComment": ...
    def get_blog_comments(self, post_id: str) -> Sequence["BlogComment"]: ...

    # Comment reactions
    def create_comment_reaction(self, data: "CommentReactionDTO") -> "CommentReaction": ...
    def get_comment_reaction(self, id: str) -> "CommentReaction": ...
    def get_comment_reactions(self, comment_id: str) -> Sequence["CommentReaction"]: ...
    def update_or_delete_comment_reaction(self, id: str, data: "CommentReactionDTO") -> "CommentReaction": ...
