from typing import Protocol, Sequence, TYPE_CHECKING, runtime_checkable

if TYPE_CHECKING:
    from tuned.dtos import (
        BlogCategoryDTO, BlogCommentDTO, BlogPostDTO, CommentReactionDTO,
        BlogPostListRequestDTO, BlogPostResponseDTO, BlogCategoryResponseDTO,
        BlogCommentResponseDTO, CommentReactionResponseDTO, PostByCategoryRequestDTO,
        BlogPostListResponseDTO
    )

@runtime_checkable
class BlogRepositoryProtocol(Protocol):
    # Blog posts
    def create_blog(self, data: "BlogPostDTO") -> "BlogPostResponseDTO": ...
    def get_blog_post_by_slug(self, slug: str) -> "BlogPostResponseDTO": ...
    def get_blog_post_by_id(self, id: str) -> "BlogPostResponseDTO": ...
    def get_featured(self) -> Sequence["BlogPostResponseDTO"]: ...
    def get_published(self, req: "BlogPostListRequestDTO") -> "BlogPostListResponseDTO": ...
    def update_or_delete_post(self, id: str, data: "BlogPostDTO") -> "BlogPostResponseDTO": ...
    def get_by_category(self, req: "PostByCategoryRequestDTO") -> Sequence["BlogPostResponseDTO"]: ...

    # Blog categories
    def create_blog_category(self, data: "BlogCategoryDTO") -> "BlogCategoryResponseDTO": ...
    def get_blog_category_by_slug(self, slug: str) -> "BlogCategoryResponseDTO": ...
    def list_blog_categories(self) -> Sequence["BlogCategoryResponseDTO"]: ...
    def update_or_delete_category(self, id: str, data: "BlogCategoryDTO") -> "BlogCategoryResponseDTO": ...

    # Blog comments
    def create_blog_comment(self, data: "BlogCommentDTO") -> "BlogCommentResponseDTO": ...
    def get_blog_comment(self, id: str) -> "BlogCommentResponseDTO": ...
    def update_or_delete_comment(self, id: str, data: "BlogCommentDTO") -> "BlogCommentResponseDTO": ...
    def get_blog_comments(self, post_id: str) -> Sequence["BlogCommentResponseDTO"]: ...

    # Comment reactions
    def create_comment_reaction(self, data: "CommentReactionDTO") -> "CommentReactionResponseDTO": ...
    def get_comment_reaction(self, id: str) -> "CommentReactionResponseDTO": ...
    def get_comment_reactions(self, comment_id: str) -> Sequence["CommentReactionResponseDTO"]: ...
    def update_or_delete_comment_reaction(self, id: str, data: "CommentReactionDTO") -> "CommentReactionResponseDTO": ...
