from typing import Protocol, Optional, Sequence, TYPE_CHECKING, runtime_checkable

if TYPE_CHECKING:
    from tuned.dtos import (
        AcademicLevelDTO, AcademicLevelResponseDTO, AcademicLevelUpdateDTO,
        DeadlineDTO, DeadlineResponseDTO, DeadlineUpdateDTO,
        FaqDTO, FaqResponseDTO, FaqUpdateDTO,
        SampleDTO, SampleResponseDTO, SampleUpdateDTO, SampleListRequestDTO,
        SampleListResponseDTO, SampleServiceResponseDTO, ServiceCategoryDTO, ServiceCategoryResponseDTO,
        ServiceCategoryUpdateDTO, ServiceDTO, ServiceResponseDTO, ServiceUpdateDTO,
        TestimonialDTO, TestimonialResponseDTO, TestimonialUpdateDTO,
        TestimonialListRequestDTO, TestimonialListResponseDTO
    )

@runtime_checkable
class AcademicLevelRepositoryProtocol(Protocol):
    def create(self, data: "AcademicLevelDTO") -> "AcademicLevelResponseDTO": ...
    def get_by_id(self, level_id: str) -> "AcademicLevelResponseDTO": ...
    def get_all(self) -> Sequence["AcademicLevelResponseDTO"]: ...
    def update(self, level_id: str, updates: "AcademicLevelUpdateDTO") -> "AcademicLevelResponseDTO": ...
    def delete(self, level_id: str) -> None: ...

@runtime_checkable
class DeadlineRepositoryProtocol(Protocol):
    def create(self, data: "DeadlineDTO") -> "DeadlineResponseDTO": ...
    def get_by_id(self, deadline_id: str) -> "DeadlineResponseDTO": ...
    def get_all(self) -> Sequence["DeadlineResponseDTO"]: ...
    def update(self, deadline_id: str, updates: "DeadlineUpdateDTO") -> "DeadlineResponseDTO": ...
    def delete(self, deadline_id: str) -> None: ...

@runtime_checkable
class FAQRepositoryProtocol(Protocol):
    def create(self, data: "FaqDTO") -> "FaqResponseDTO": ...
    def get_by_id(self, faq_id: str) -> "FaqResponseDTO": ...
    def get_all(self, category: Optional[str] = None) -> Sequence["FaqResponseDTO"]: ...
    def get_categories(self) -> Sequence[str]: ...
    def update(self, faq_id: str, updates: "FaqUpdateDTO") -> "FaqResponseDTO": ...
    def delete(self, faq_id: str) -> None: ...

@runtime_checkable
class SampleRepositoryProtocol(Protocol):
    def create(self, data: "SampleDTO") -> "SampleResponseDTO": ...
    def get_by_id(self, sample_id: str) -> "SampleResponseDTO": ...
    def get_by_slug(self, slug: str) -> "SampleResponseDTO": ...
    def get_featured(self) -> Sequence["SampleResponseDTO"]: ...
    def get_all(self) -> Sequence["SampleResponseDTO"]: ...
    def list_all(self, req: "SampleListRequestDTO") -> "SampleListResponseDTO": ...
    def update(self, sample_id: str, updates: "SampleUpdateDTO") -> "SampleResponseDTO": ...
    def delete(self, sample_id: str) -> None: ...
    def get_samples_by_service_id(self, service_id: str) -> Sequence["SampleResponseDTO"]: ...
    def get_related_samples(self, slug: str) -> Sequence["SampleResponseDTO"]: ...
    def get_distinct_services(self) -> Sequence["SampleServiceResponseDTO"]: ...

@runtime_checkable
class ServiceCategoryRepositoryProtocol(Protocol):
    def create(self, data: "ServiceCategoryDTO") -> "ServiceCategoryResponseDTO": ...
    def get_by_id(self, category_id: str) -> "ServiceCategoryResponseDTO": ...
    def get_all(self) -> Sequence["ServiceCategoryResponseDTO"]: ...
    def update(self, category_id: str, updates: "ServiceCategoryUpdateDTO") -> "ServiceCategoryResponseDTO": ...
    def delete(self, category_id: str) -> None: ...

@runtime_checkable
class ServiceRepositoryProtocol(Protocol):
    def create(self, data: "ServiceDTO") -> "ServiceResponseDTO": ...
    def get_by_id(self, service_id: str) -> "ServiceResponseDTO": ...
    def get_by_slug(self, slug: str) -> "ServiceResponseDTO": ...
    def get_all(self, active_only: bool = True) -> Sequence["ServiceResponseDTO"]: ...
    def get_featured(self) -> Sequence["ServiceResponseDTO"]: ...
    def update(self, service_id: str, updates: "ServiceUpdateDTO") -> "ServiceResponseDTO": ...
    def delete(self, service_id: str) -> None: ...
    def get_services_by_category(self, category_id: str) -> Sequence["ServiceResponseDTO"]: ...
    def get_service_mix(self, client_id: str) -> Sequence[tuple[str, int]]: ...

@runtime_checkable
class TestimonialRepositoryProtocol(Protocol):
    def create(self, data: "TestimonialDTO") -> "TestimonialResponseDTO": ...
    def get_by_id(self, testimonial_id: str) -> "TestimonialResponseDTO": ...
    def get_approved(self, service_id: Optional[str] = None) -> Sequence["TestimonialResponseDTO"]: ...
    def get_approved_paginated(self, req: "TestimonialListRequestDTO") -> "TestimonialListResponseDTO": ...
    def get_pending(self) -> Sequence["TestimonialResponseDTO"]: ...
    def approve(self, testimonial_id: str) -> "TestimonialResponseDTO": ...
    def update(self, testimonial_id: str, updates: "TestimonialUpdateDTO") -> "TestimonialResponseDTO": ...
    def delete(self, testimonial_id: str) -> None: ...
