from typing import Protocol, Optional, runtime_checkable
from tuned.models.media import MediaAsset
from tuned.dtos.media import MediaAssetCreateDTO

@runtime_checkable
class MediaRepositoryProtocol(Protocol):
    def create(self, data: MediaAssetCreateDTO) -> MediaAsset: ...
    def get_by_id(self, asset_id: str) -> Optional[MediaAsset]: ...
    def get_by_storage_path(self, storage_path: str) -> Optional[MediaAsset]: ...
    def delete(self, asset_id: str) -> None: ...
    def save(self) -> None: ...
    def rollback(self) -> None: ...
