from typing import Protocol, Optional, Sequence, TYPE_CHECKING, runtime_checkable

if TYPE_CHECKING:
    from tuned.models import Order, OrderFile
    from tuned.models.payment import Discount
    from tuned.dtos.order import CreateOrderRequestDTO, OrderDraftCreateDTO

@runtime_checkable
class OrderRepositoryProtocol(Protocol):
    def get_active_orders(self, client_id: str) -> Sequence["Order"]: ...
    def get_paid_order_count(self, client_id: str) -> int: ...
    def get_latest_active_order(self, client_id: str) -> Optional["Order"]: ...
    def get_upcoming_deadlines(self, client_id: str, limit: int = 3) -> Sequence["Order"]: ...
    def get_project_lifecycle(self, client_id: str) -> Sequence[tuple[str, int]]: ...
    def get_order_by_id_for_client(self, order_id: str, client_id: str) -> "Order": ...
    def get_order_for_reorder(self, order_id: str, client_id: str) -> "Order": ...
    def apply_discount(self, order_id: str, client_id: str, discount_amount: float) -> "Order": ...
    def create_reorder(self, source: "Order", client_id: str) -> "Order": ...
    def create_order(self, client_id: str, dto: "CreateOrderRequestDTO", total_price: float, subtotal: float) -> "Order": ...
    def get_discount_by_code(self, code: str) -> Optional["Discount"]: ...
    def link_discount_to_order(self, order: "Order", discount: "Discount", amount: float) -> None: ...
    def create_order_file(self, order_id: str, filename: str, file_path: str) -> "OrderFile": ...
    def upsert_draft(self, dto: "OrderDraftCreateDTO") -> "Order": ...
    def get_draft(self, user_id: str) -> Optional["Order"]: ...
    def save(self) -> None: ...
    def rollback(self) -> None: ...
