from typing import Protocol, Sequence, TYPE_CHECKING, runtime_checkable

if TYPE_CHECKING:
    from tuned.dtos.order_delivery import(
        CreateOrderDeliveryDTO, OrderDeliveryResponseDTO,
        UpdateOrderDeliveryStatusDTO, AddDeliveryFilesDTO
    )
from tuned.models.order_delivery import OrderDelivery
@runtime_checkable
class OrderDeliveryRepositoryProtocol(Protocol):
    def create_order_delivery(self, data: "CreateOrderDeliveryDTO") -> "OrderDelivery": ...
    def get_by_id(self, delivery_id: str) -> "OrderDelivery": ...
    def get_order_deliveries(self, order_id: str) -> Sequence["OrderDelivery"]: ...
    def update_status(self, delivery_id: str, data: "UpdateOrderDeliveryStatusDTO") -> "OrderDelivery": ...
    def add_files(self, delivery_id: str, data: "AddDeliveryFilesDTO") -> "OrderDelivery": ...
    def mark_client_notified(self, delivery_id: str) -> "OrderDelivery": ...
    def delete(self, delivery_id: str, user_id: str) -> None: ...
