from typing import Protocol, TYPE_CHECKING, runtime_checkable, List, Tuple

if TYPE_CHECKING:
    from tuned.dtos import (
        PaymentCreateDTO, PaymentUpdateDTO, PaymentResponseDTO,
        InvoiceCreateDTO, InvoiceUpdateDTO, InvoiceResponseDTO,
        TransactionCreateDTO, TransactionResponseDTO,
        DiscountCreateDTO, DiscountUpdateDTO, DiscountResponseDTO,
        RefundCreateDTO, RefundUpdateDTO, RefundResponseDTO,
        AcceptedMethodCreateDTO, AcceptedMethodUpdateDTO, AcceptedMethodResponseDTO
    )

@runtime_checkable
class PaymentsManagerProtocol(Protocol):
    def create(self, data: "PaymentCreateDTO") -> "PaymentResponseDTO": ...
    def get_by_id(self, payment_id: str) -> "PaymentResponseDTO": ...
    def get_by_order_id(self, order_id: str) -> List["PaymentResponseDTO"]: ...
    def update(self, payment_id: str, data: "PaymentUpdateDTO") -> "PaymentResponseDTO": ...
    def get_spending_velocity(self, client_id: str, months: int = 6) -> List[Tuple[str, float]]: ...

@runtime_checkable
class InvoiceManagerProtocol(Protocol):
    def create(self, data: "InvoiceCreateDTO") -> "InvoiceResponseDTO": ...
    def get_by_id(self, invoice_id: str) -> "InvoiceResponseDTO": ...
    def get_by_number(self, invoice_number: str) -> "InvoiceResponseDTO": ...
    def update(self, invoice_id: str, data: "InvoiceUpdateDTO") -> "InvoiceResponseDTO": ...

@runtime_checkable
class TransactionManagerProtocol(Protocol):
    def create(self, data: "TransactionCreateDTO") -> "TransactionResponseDTO": ...
    def get_by_id(self, transaction_id: str) -> "TransactionResponseDTO": ...
    def get_by_payment_id(self, payment_id: str) -> List["TransactionResponseDTO"]: ...

@runtime_checkable
class DiscountManagerProtocol(Protocol):
    def create(self, data: "DiscountCreateDTO") -> "DiscountResponseDTO": ...
    def get_by_id(self, discount_id: str) -> "DiscountResponseDTO": ...
    def get_by_code(self, code: str) -> "DiscountResponseDTO": ...
    def update(self, discount_id: str, data: "DiscountUpdateDTO") -> "DiscountResponseDTO": ...
    def increment_usage(self, discount_id: str) -> "DiscountResponseDTO": ...

@runtime_checkable
class RefundManagerProtocol(Protocol):
    def create(self, data: "RefundCreateDTO") -> "RefundResponseDTO": ...
    def get_by_id(self, refund_id: str) -> "RefundResponseDTO": ...
    def update_status(self, refund_id: str, data: "RefundUpdateDTO") -> "RefundResponseDTO": ...

@runtime_checkable
class AcceptedMethodManagerProtocol(Protocol):
    def create(self, data: "AcceptedMethodCreateDTO") -> "AcceptedMethodResponseDTO": ...
    def update(self, method_id: str, data: "AcceptedMethodUpdateDTO") -> "AcceptedMethodResponseDTO": ...
    def get_by_id(self, method_id: str) -> "AcceptedMethodResponseDTO": ...
    def get_all_active(self) -> List["AcceptedMethodResponseDTO"]: ...

@runtime_checkable
class PaymentRepositoryProtocol(Protocol):
    @property
    def payment(self) -> PaymentsManagerProtocol: ...
    @property
    def invoice(self) -> InvoiceManagerProtocol: ...
    @property
    def transaction(self) -> TransactionManagerProtocol: ...
    @property
    def discount(self) -> DiscountManagerProtocol: ...
    @property
    def refund(self) -> RefundManagerProtocol: ...
    @property
    def accepted_method(self) -> AcceptedMethodManagerProtocol: ...
