from typing import Protocol, Sequence, TYPE_CHECKING, runtime_checkable

if TYPE_CHECKING:
    from tuned.dtos import (
        PricingCategoryDTO, PricingCategoryResponseDTO, PricingCategoryUpdateDTO,
        PriceRateDTO, PriceRateResponseDTO, PriceRateUpdateDTO, PriceRateLookupDTO
    )

@runtime_checkable
class PricingCategoryRepositoryProtocol(Protocol):
    def create(self, data: "PricingCategoryDTO") -> "PricingCategoryResponseDTO": ...
    def get_by_id(self, category_id: str) -> "PricingCategoryResponseDTO": ...
    def get_all(self) -> Sequence["PricingCategoryResponseDTO"]: ...
    def update(self, category_id: str, updates: "PricingCategoryUpdateDTO") -> "PricingCategoryResponseDTO": ...
    def delete(self, category_id: str) -> None: ...

@runtime_checkable
class PriceRateRepositoryProtocol(Protocol):
    def create(self, data: "PriceRateDTO") -> "PriceRateResponseDTO": ...
    def get_by_id(self, rate_id: str) -> "PriceRateResponseDTO": ...
    def get_by_dimensions(self, lookup: "PriceRateLookupDTO") -> "PriceRateResponseDTO": ...
    def get_by_category(self, pricing_category_id: str, active_only: bool = True) -> Sequence["PriceRateResponseDTO"]: ...
    def update(self, rate_id: str, updates: "PriceRateUpdateDTO") -> "PriceRateResponseDTO": ...
    def delete(self, rate_id: str) -> None: ...
