from typing import Protocol, Optional, Sequence, TYPE_CHECKING, runtime_checkable
from datetime import datetime

if TYPE_CHECKING:
    from tuned.dtos import ReferralResponseDTO
    from tuned.models.enums import ReferralStatus

@runtime_checkable
class ReferralRepositoryProtocol(Protocol):
    def create(self, referrer_id: str, referred_id: str, code: str, points_earned: int = 0) -> "ReferralResponseDTO": ...
    def get_by_id(self, id: str) -> Optional["ReferralResponseDTO"]: ...
    def get_by_referred_id(self, referred_id: str) -> Optional["ReferralResponseDTO"]: ...
    def get_by_code(self, code: str) -> Optional["ReferralResponseDTO"]: ...
    def get_active_by_referrer(self, referrer_id: str) -> Sequence["ReferralResponseDTO"]: ...
    def update_points_and_status(
        self, 
        id: str, 
        added_points: int, 
        status: "ReferralStatus",
        completed_at: Optional[datetime] = None,
        expires_at: Optional[datetime] = None
    ) -> Optional["ReferralResponseDTO"]: ...
    def count_monthly_completed_referrals(self, referrer_id: str, year: int, month: int) -> int: ...
    def get_referral_growth(self, referrer_id: str, months: int = 6) -> Sequence[tuple[str, float]]: ...
    def save(self) -> None: ...
    def rollback(self) -> None: ...
