from typing import Protocol, List, Any, runtime_checkable

@runtime_checkable
class SearchRepositoryProtocol(Protocol):
    def search_services(self, pattern: str, offset: int, limit: int) -> List[Any]: ...
    def search_samples(self, pattern: str, offset: int, limit: int) -> List[Any]: ...
    def search_blogs(self, pattern: str, offset: int, limit: int) -> List[Any]: ...
    def search_faqs(self, pattern: str, offset: int, limit: int) -> List[Any]: ...
    def search_tags(self, pattern: str, offset: int, limit: int) -> List[Any]: ...
