from typing import Protocol, Optional, Sequence, TYPE_CHECKING, runtime_checkable
from datetime import datetime

if TYPE_CHECKING:
    from tuned.models.user import User
    from tuned.dtos import CreateUserDTO, UpdateUserDTO, ActionableAlertDTO

@runtime_checkable
class UserRepositoryProtocol(Protocol):
    def create_user(self, user_data: "CreateUserDTO") -> "User": ...
    def get_user_by_id(self, user_id: str) -> "User": ...
    def get_user_by_email(self, email: str) -> "User": ...
    def get_user_by_username(self, username: str) -> "User": ...
    def get_by_referral_code(self, referral_code: str) -> Optional["User"]: ...
    def get_admin_user(self) -> "User": ...
    def update_user(self, updates: "UpdateUserDTO", actor_id: str) -> "User": ...
    def increment_failed_login_attempts(self, user_id: str) -> int: ...
    def generate_verification_token(self, user_id: str) -> tuple["User", str]: ...
    def confirm_email_verification(self, user_id: str, raw_token: str) -> "User": ...
    def get_user_for_resend(self, email: str) -> Optional["User"]: ...
    def get_actionable_alerts(self, client_id: str) -> Sequence["ActionableAlertDTO"]: ...
    def save(self) -> None: ...
    def rollback(self) -> None: ...
