from typing import Protocol, Optional, Sequence, TYPE_CHECKING, runtime_checkable
from datetime import datetime

if TYPE_CHECKING:
    from tuned.dtos import (
        UserResponseDTO, CreateUserDTO, LoginRequestDTO, UpdateUserDTO,
        ActivityLogCreateDTO, EmailVerificationResendDTO, EmailVerifyConfirmDTO,
        ProfileResponseDTO, UpdateProfileRequestDTO, ChangePasswordRequestDTO,
        ReferralResponseDTO, RewardCalculationResultDTO, ReferralRedemptionResultDTO
    )
    from tuned.dtos.base import BaseRequestDTO

@runtime_checkable
class UserServiceProtocol(Protocol):
    def login_user(self, credentials: "LoginRequestDTO") -> tuple[bool, dict]: ...
    def create_user(self, data: "CreateUserDTO", locale: "BaseRequestDTO", referred_by_code: Optional[str] = None) -> dict: ...
    def resend_verification_email(self, dto: "EmailVerificationResendDTO") -> bool: ...
    def confirm_email_verification(self, dto: "EmailVerifyConfirmDTO") -> tuple[bool, str]: ...
    def get_user_by_email(self, email: str) -> dict: ...
    def get_profile(self, user_id: str) -> dict: ...
    def update_profile(self, user_id: str, data: "UpdateProfileRequestDTO", locale: "BaseRequestDTO") -> dict: ...
    def change_password(self, user_id: str, data: "ChangePasswordRequestDTO", locale: "BaseRequestDTO") -> bool: ...
    def upload_avatar(self, user_id: str, file: any, locale: "BaseRequestDTO") -> dict: ...
    def delete_avatar(self, user_id: str, locale: "BaseRequestDTO") -> dict: ...

@runtime_checkable
class ReferralInterfaceProtocol(Protocol):
    def get_by_id(self, id: str) -> Optional["ReferralResponseDTO"]: ...
    def get_by_referred_id(self, referred_id: str) -> Optional["ReferralResponseDTO"]: ...
    def get_by_code(self, code: str) -> Optional["ReferralResponseDTO"]: ...
    def get_active_by_referrer(self, referrer_id: str) -> Sequence["ReferralResponseDTO"]: ...
    def get_referral_growth(self, referrer_id: str) -> Sequence[tuple[str, float]]: ...
    def count_monthly_completed_referrals(self, referrer_id: str, year: int, month: int) -> Optional[int]: ...
    def process_signup(self, new_user_id: str, referral_code: str) -> None: ...
    def reward_referrer(self, referred_id: str, order_value: float) -> None: ...
    def redeem_points(self, user_id: str, order_id: str, points_to_redeem: int) -> "ReferralRedemptionResultDTO": ...
