from typing import Protocol, Optional, Sequence, TYPE_CHECKING, runtime_checkable, Any, Dict
from werkzeug.datastructures import FileStorage
from tuned.models.enums import AssetOwnerType

if TYPE_CHECKING:
    from tuned.dtos import (
        UserResponseDTO, CreateUserDTO, LoginRequestDTO, UpdateUserDTO,
        ActivityLogCreateDTO, ActivityLogResponseDTO, EmailVerificationResendDTO, EmailVerifyConfirmDTO,
        ProfileResponseDTO, UpdateProfileRequestDTO, ChangePasswordRequestDTO,
        ReferralResponseDTO, RewardCalculationResultDTO, ReferralRedemptionResultDTO
    )
    from tuned.dtos.base import BaseRequestDTO

@runtime_checkable
class ActivityLogServiceProtocol(Protocol):
    def log(self, data: "ActivityLogCreateDTO") -> "ActivityLogResponseDTO": ...

@runtime_checkable
class UserServiceProtocol(Protocol):
    def login_user(self, credentials: "LoginRequestDTO") -> tuple[bool, Dict[str, Any]]: ...
    def create_user(self, data: "CreateUserDTO", locale: "BaseRequestDTO", referred_by_code: Optional[str] = None) -> Dict[str, Any]: ...
    def resend_verification_email(self, dto: "EmailVerificationResendDTO") -> bool: ...
    def confirm_email_verification(self, dto: "EmailVerifyConfirmDTO") -> tuple[bool, str]: ...
    def get_user_by_email(self, email: str) -> Dict[str, Any]: ...
    def get_profile(self, user_id: str) -> Dict[str, Any]: ...
    def update_profile(self, user_id: str, data: "UpdateProfileRequestDTO", locale: "BaseRequestDTO") -> Dict[str, Any]: ...
    def change_password(self, user_id: str, data: "ChangePasswordRequestDTO", locale: "BaseRequestDTO") -> bool: ...
    def upload_avatar(self, user_id: str, file: Any, locale: "BaseRequestDTO") -> Dict[str, Any]: ...
    def delete_avatar(self, user_id: str, locale: "BaseRequestDTO") -> Dict[str, Any]: ...

@runtime_checkable
class ReferralInterfaceProtocol(Protocol):
    def get_by_id(self, id: str) -> Optional["ReferralResponseDTO"]: ...
    def get_by_referred_id(self, referred_id: str) -> Optional["ReferralResponseDTO"]: ...
    def get_by_code(self, code: str) -> Optional["ReferralResponseDTO"]: ...
    def get_active_by_referrer(self, referrer_id: str) -> Sequence["ReferralResponseDTO"]: ...
    def get_referral_growth(self, referrer_id: str) -> Sequence[tuple[str, float]]: ...
    def count_monthly_completed_referrals(self, referrer_id: str, year: int, month: int) -> int: ...
    def process_signup(self, new_user_id: str, referral_code: str) -> None: ...
    def reward_referrer(self, referred_id: str, order_value: float) -> None: ...
    def redeem_points(self, user_id: str, order_id: str, points_to_redeem: int) -> "ReferralRedemptionResultDTO": ...


@runtime_checkable
class MediaServiceProtocol(Protocol):
    def upload_file(
        self,
        file: FileStorage,
        owner_type: AssetOwnerType,
        owner_id: str,
        is_public: bool = True,
        alt_text: Optional[str] = None
    ) -> Any: ...
    
    def get_by_id(self, asset_id: str) -> Any: ...
    def verify_download_permission(self, asset_id: str, user_id: str) -> bool: ...
    def create_bulk_zip(self, asset_ids: list[str], user_id: str) -> str: ...
    def create_order_zip(self, order_id: str, user_id: str) -> str: ...
    def create_delivery_zip(self, delivery_id: str, user_id: str) -> str: ...
    def delete_media(self, asset_id: str) -> None: ...

