class Variables:
    USER_LOGIN_ACTION = "user_login"
    USER_REGISTER_ACTION = "user_register"
    USER_ENTITY_TYPE = "User"
    EMAIL_VERIFICATION_ACTION = "email_verification"
    PROFILE_UPDATE_ACTION = "user_profile_update"
    PASSWORD_CHANGE_ACTION = "password_change"
    AVATAR_UPLOAD_ACTION = "avatar_upload"
    AVATAR_UPDATE_ACTION = "avatar_update"
    AVATAR_DELETE_ACTION = "avatar_delete"

    ORDER_ENTITY_TYPE = "Order"
    
    PAYMENT_CREATE_ACTION = "payment_create"
    PAYMENT_UPDATE_ACTION = "payment_update"
    INVOICE_CREATE_ACTION = "invoice_create"
    INVOICE_UPDATE_ACTION = "invoice_update"
    DISCOUNT_CREATE_ACTION = "discount_create"
    DISCOUNT_UPDATE_ACTION = "discount_update"
    DISCOUNT_APPLY_ACTION = "discount_apply"
    REFUND_CREATE_ACTION = "refund_create"
    REFUND_UPDATE_ACTION = "refund_update"
    TRANSACTION_CREATE_ACTION = "transaction_create"
    
    ACCEPTED_METHOD_CREATE_ACTION = "accepted_method_create"
    ACCEPTED_METHOD_UPDATE_ACTION = "accepted_method_update"
    
    PAYMENT_ENTITY_TYPE = "Payment"
    INVOICE_ENTITY_TYPE = "Invoice"
    DISCOUNT_ENTITY_TYPE = "Discount"
    REFUND_ENTITY_TYPE = "Refund"
    TRANSACTION_ENTITY_TYPE = "Transaction"

    ENTITY_TYPE_REFERRAL = "Referral"
    REFERRAL_SIGNUP_ACTION = "referral_signup"
    REFERRAL_POINTS_EARNED_ACTION = "referral_points_earned"
    REFERRAL_POINTS_REDEEMED_ACTION = "referral_points_redeemed"

    OK = "ok"
    NOT_FOUND = "not_found"
    ALREADY_VERIFIED = "already_verified"

    PRODUCTION = "production"
    DEVELOPMENT = "development"
    # ALREADY_EXISTS = "already_exists"
    # INVALID = "invalid"
    # NO_TOKEN = "no_token"

    ORDER_FILE_ENTITY_TYPE = "OrderFile"
    ORDER_ENTITY_TYPE = "Order"
    ORDER_REORDERED = "order_reordered"
    ORDER_CREATED = "order_created"
    ORDER_FILES_UPLOADED = "order_files_uploaded"
    ORDER_PAID = "order_paid"
    ORDER_CANCELLED = "order_cancelled"
    ORDER_DELIVERED = "order_delivered"
    ORDER_COMPLETED = "order_completed"
    ORDER_REFUNDED = "refunded"
    ORDER_PARTIALLY_REFUNDED = "partially_refunded"
    ORDER_LATE = "late"
    ORDER_LATE_COMPLETED = "late_completed"
    
    