class Variables:
    USER_LOGIN_ACTION = "user_login"
    USER_REGISTER_ACTION = "user_register"
    USER_ENTITY_TYPE = "User"
    EMAIL_VERIFICATION_ACTION = "email_verification"
    PROFILE_UPDATE_ACTION = "user_profile_update"
    PASSWORD_CHANGE_ACTION = "password_change"
    AVATAR_UPLOAD_ACTION = "avatar_upload"
    AVATAR_UPDATE_ACTION = "avatar_update"
    AVATAR_DELETE_ACTION = "avatar_delete"

    # ORDER_ENTITY_TYPE = "Order"
    
    PAYMENT_CREATE_ACTION = "payment_create"
    PAYMENT_UPDATE_ACTION = "payment_update"
    INVOICE_CREATE_ACTION = "invoice_create"
    INVOICE_UPDATE_ACTION = "invoice_update"
    DISCOUNT_CREATE_ACTION = "discount_create"
    DISCOUNT_UPDATE_ACTION = "discount_update"
    DISCOUNT_APPLY_ACTION = "discount_apply"
    REFUND_CREATE_ACTION = "refund_create"
    REFUND_UPDATE_ACTION = "refund_update"
    TRANSACTION_CREATE_ACTION = "transaction_create"
    
    ACCEPTED_METHOD_CREATE_ACTION = "accepted_method_create"
    ACCEPTED_METHOD_UPDATE_ACTION = "accepted_method_update"
    
    PAYMENT_ENTITY_TYPE = "Payment"
    INVOICE_ENTITY_TYPE = "Invoice"
    DISCOUNT_ENTITY_TYPE = "Discount"
    REFUND_ENTITY_TYPE = "Refund"
    TRANSACTION_ENTITY_TYPE = "Transaction"

    ENTITY_TYPE_REFERRAL = "Referral"
    REFERRAL_SIGNUP_ACTION = "referral_signup"
    REFERRAL_POINTS_EARNED_ACTION = "referral_points_earned"
    REFERRAL_POINTS_REDEEMED_ACTION = "referral_points_redeemed"

    OK = "ok"
    NOT_FOUND = "not_found"
    ALREADY_VERIFIED = "already_verified"

    PRODUCTION = "production"
    DEVELOPMENT = "development"
    # ALREADY_EXISTS = "already_exists"
    # INVALID = "invalid"
    # NO_TOKEN = "no_token"

    ORDER_FILE_ENTITY_TYPE = "OrderFile"
    ORDER_DRAFT_CREATED = "order_draft_created"
    ORDER_ENTITY_TYPE = "Order"
    ORDER_REORDERED = "order_reordered"
    ORDER_CREATED = "order_created"
    ORDER_FILES_UPLOADED = "order_files_uploaded"
    ORDER_PAID = "order_paid"
    ORDER_CANCELLED = "order_cancelled"
    ORDER_DELIVERED = "order_delivered"
    ORDER_COMPLETED = "order_completed"
    ORDER_REFUNDED = "refunded"
    ORDER_PARTIALLY_REFUNDED = "partially_refunded"
    ORDER_LATE = "late"
    ORDER_LATE_COMPLETED = "late_completed"

    ORDER_DELIVERY_CREATED = "order_delivery_created"
    ORDER_DELIVERY_UPDATED = "order_delivery_updated"
    ORDER_DELIVERY_DELETED = "order_delivery_deleted"
    ORDER_DELIVERY_FILE_UPLOADED_ACTION = "order_delivery_file_uploaded"
    ORDER_DELIVERY_ENTITY_TYPE = "OrderDelivery"
    
    BLOG_POST_CREATED = "blog_post_created"
    BLOG_POST_UPDATED = "blog_post_updated"
    BLOG_POST_DELETED = "blog_post_deleted"
    BLOG_POST_ENTITY_TYPE = "BlogPost"

    BLOG_COMMENT_CREATED = "blog_comment_created"
    BLOG_COMMENT_UPDATED = "blog_comment_updated"
    BLOG_COMMENT_DELETED = "blog_comment_deleted"
    BLOG_COMMENT_ENTITY_TYPE = "BlogComment"

    BLOG_CATEGORY_CREATED = "blog_category_created"
    BLOG_CATEGORY_UPDATED = "blog_category_updated"
    BLOG_CATEGORY_DELETED = "blog_category_deleted"
    BLOG_CATEGORY_ENTITY_TYPE = "BlogCategory"

    BLOG_COMMENT_REACTION_CREATED = "blog_comment_reaction_created"
    BLOG_COMMENT_REACTION_UPDATED = "blog_comment_reaction_updated"
    BLOG_COMMENT_REACTION_DELETED = "blog_comment_reaction_deleted"
    BLOG_COMMENT_REACTION_ENTITY_TYPE = "BlogCommentReaction"

    NEWSLETTER_SUBSCRIBER_SUBSCRIBED = "newsletter_subscriber_subscribed"
    NEWSLETTER_SUBSCRIBER_UNSUBSCRIBED = "newsletter_subscriber_unsubscribed"
    NEWSLETTER_SUBSCRIBER_RESUBSCRIBED = "newsletter_subscriber_resubscribed"
    NEWSLETTER_SUBSCRIBER_ENTITY_TYPE = "NewsletterSubscriber"

    SERVICE_CATEGORY_ENTITY_TYPE = "ServiceCategory"
    SERVICE_CATEGORY_CREATE_ACTION = "service_category_create"
    SERVICE_CATEGORY_UPDATE_ACTION = "service_category_update"
    SERVICE_CATEGORY_DELETE_ACTION = "service_category_delete"

    SERVICE_ENTITY_TYPE = "Service"
    SERVICE_CREATE_ACTION = "service_create"
    SERVICE_UPDATE_ACTION = "service_update"
    SERVICE_DELETE_ACTION = "service_delete"

    CHAT_ENTITY_TYPE = "Chat"
    CHAT_MESSAGE_ENTITY_TYPE = "ChatMessage"
    CHAT_CREATED_ACTION = "chat_created"
    CHAT_MESSAGE_SENT_ACTION = "chat_message_sent"
    CHAT_STATUS_CHANGED_ACTION = "chat_status_changed"
    CHAT_ASSIGNED_ACTION = "chat_assigned"

    SAMPLE_ENTITY_TYPE = "Sample"
    SAMPLE_CREATE_ACTION = "sample_create"
    SAMPLE_UPDATE_ACTION = "sample_update"
    SAMPLE_DELETE_ACTION = "sample_delete"