from typing import Protocol, Optional, Sequence, TYPE_CHECKING, runtime_checkable, Any
from datetime import datetime

if TYPE_CHECKING:
    from tuned.models import ActivityLog, EmailLog, OrderStatusHistory, PriceHistory, Order
    from tuned.models.user import User
    from tuned.dtos import (
        CreateUserDTO, UpdateUserDTO, ActionableAlertDTO, ReferralResponseDTO,
        BlogCategoryDTO, BlogCommentDTO, BlogPostDTO, CommentReactionDTO,
        BlogPostListRequestDTO, BlogPostResponseDTO, BlogCategoryResponseDTO,
        BlogCommentResponseDTO, CommentReactionResponseDTO, PostByCategoryRequestDTO,
        BlogPostListResponseDTO,
        AcademicLevelDTO, AcademicLevelResponseDTO, DeadlineDTO, DeadlineResponseDTO,
        FaqDTO, FaqResponseDTO, SampleDTO, SampleResponseDTO, SampleListRequestDTO,
        SampleListResponseDTO, ServiceCategoryDTO, ServiceCategoryResponseDTO,
        ServiceDTO, ServiceResponseDTO, TestimonialDTO, TestimonialResponseDTO,
        PricingCategoryDTO, PricingCategoryResponseDTO, PriceRateDTO, PriceRateResponseDTO,
        PriceRateLookupDTO, ActivityLogCreateDTO, ActivityLogResponseDTO,
        ActivityLogFilterDTO, EmailLogCreateDTO, EmailLogResponseDTO,
        EmailLogFilterDTO, EmailLogUpdateDTO, OrderStatusHistoryCreateDTO,
        OrderStatusHistoryResponseDTO, PriceHistoryCreateDTO, PriceHistoryResponseDTO,
        PaymentCreateDTO, PaymentUpdateDTO, PaymentResponseDTO,
        InvoiceCreateDTO, InvoiceUpdateDTO, InvoiceResponseDTO,
        TransactionCreateDTO, TransactionResponseDTO,
        DiscountCreateDTO, DiscountUpdateDTO, DiscountResponseDTO,
        RefundCreateDTO, RefundUpdateDTO, RefundResponseDTO,
        AcceptedMethodCreateDTO, AcceptedMethodUpdateDTO, AcceptedMethodResponseDTO,
        AllPreferencesResponseDTO
    )
    from tuned.models.enums import ReferralStatus

@runtime_checkable
class UserRepositoryProtocol(Protocol):
    def create_user(self, user_data: "CreateUserDTO") -> "User": ...
    def get_user_by_id(self, user_id: str) -> "User": ...
    def get_user_by_email(self, email: str) -> "User": ...
    def get_user_by_username(self, username: str) -> "User": ...
    def get_by_referral_code(self, referral_code: str) -> Optional["User"]: ...
    def get_admin_user(self) -> "User": ...
    def update_user(self, updates: "UpdateUserDTO", actor_id: str) -> "User": ...
    def increment_failed_login_attempts(self, user_id: str) -> int: ...
    def generate_verification_token(self, user_id: str) -> tuple["User", str]: ...
    def confirm_email_verification(self, user_id: str, raw_token: str) -> "User": ...
    def get_user_for_resend(self, email: str) -> Optional["User"]: ...
    def get_actionable_alerts(self, client_id: str) -> Sequence["ActionableAlertDTO"]: ...

@runtime_checkable
class ReferralRepositoryProtocol(Protocol):
    def create(self, referrer_id: str, referred_id: str, code: str, points_earned: int = 0) -> "ReferralResponseDTO": ...
    def get_by_id(self, id: str) -> Optional["ReferralResponseDTO"]: ...
    def get_by_referred_id(self, referred_id: str) -> Optional["ReferralResponseDTO"]: ...
    def get_by_code(self, code: str) -> Optional["ReferralResponseDTO"]: ...
    def get_active_by_referrer(self, referrer_id: str) -> Sequence["ReferralResponseDTO"]: ...
    def update_points_and_status(
        self, 
        id: str, 
        added_points: int, 
        status: "ReferralStatus",
        completed_at: Optional[datetime] = None,
        expires_at: Optional[datetime] = None
    ) -> Optional["ReferralResponseDTO"]: ...
    def count_monthly_completed_referrals(self, referrer_id: str, year: int, month: int) -> int: ...
    def get_referral_growth(self, referrer_id: str, months: int = 6) -> Sequence[tuple[str, float]]: ...

@runtime_checkable
class BlogRepositoryProtocol(Protocol):
    # Blog posts
    def create_blog(self, data: "BlogPostDTO") -> "BlogPostResponseDTO": ...
    def get_blog_post_by_slug(self, slug: str) -> "BlogPostResponseDTO": ...
    def get_blog_post_by_id(self, id: str) -> "BlogPostResponseDTO": ...
    def get_featured(self) -> Sequence["BlogPostResponseDTO"]: ...
    def get_published(self, req: "BlogPostListRequestDTO") -> "BlogPostListResponseDTO": ...
    def update_or_delete_post(self, id: str, data: "BlogPostDTO") -> "BlogPostResponseDTO": ...
    def get_by_category(self, req: "PostByCategoryRequestDTO") -> Sequence["BlogPostResponseDTO"]: ...

    # Blog categories
    def create_blog_category(self, data: "BlogCategoryDTO") -> "BlogCategoryResponseDTO": ...
    def get_blog_category_by_slug(self, slug: str) -> "BlogCategoryResponseDTO": ...
    def list_blog_categories(self) -> Sequence["BlogCategoryResponseDTO"]: ...
    def update_or_delete_category(self, id: str, data: "BlogCategoryDTO") -> "BlogCategoryResponseDTO": ...

    # Blog comments
    def create_blog_comment(self, data: "BlogCommentDTO") -> "BlogCommentResponseDTO": ...
    def get_blog_comment(self, id: str) -> "BlogCommentResponseDTO": ...
    def update_or_delete_comment(self, id: str, data: "BlogCommentDTO") -> "BlogCommentResponseDTO": ...
    def get_blog_comments(self, post_id: str) -> Sequence["BlogCommentResponseDTO"]: ...

    # Comment reactions
    def create_comment_reaction(self, data: "CommentReactionDTO") -> "CommentReactionResponseDTO": ...
    def get_comment_reaction(self, id: str) -> "CommentReactionResponseDTO": ...
    def get_comment_reactions(self, comment_id: str) -> Sequence["CommentReactionResponseDTO"]: ...
    def update_or_delete_comment_reaction(self, id: str, data: "CommentReactionDTO") -> "CommentReactionResponseDTO": ...

@runtime_checkable
class AcademicLevelRepositoryProtocol(Protocol):
    def create(self, data: "AcademicLevelDTO") -> "AcademicLevelResponseDTO": ...
    def get_by_id(self, level_id: str) -> "AcademicLevelResponseDTO": ...
    def get_all(self) -> Sequence["AcademicLevelResponseDTO"]: ...
    def update(self, level_id: str, updates: dict[str, Any]) -> "AcademicLevelResponseDTO": ...
    def delete(self, level_id: str) -> None: ...

@runtime_checkable
class DeadlineRepositoryProtocol(Protocol):
    def create(self, data: "DeadlineDTO") -> "DeadlineResponseDTO": ...
    def get_by_id(self, deadline_id: str) -> "DeadlineResponseDTO": ...
    def get_all(self) -> Sequence["DeadlineResponseDTO"]: ...
    def update(self, deadline_id: str, updates: dict[str, Any]) -> "DeadlineResponseDTO": ...
    def delete(self, deadline_id: str) -> None: ...

@runtime_checkable
class FAQRepositoryProtocol(Protocol):
    def create(self, data: "FaqDTO") -> "FaqResponseDTO": ...
    def get_by_id(self, faq_id: str) -> "FaqResponseDTO": ...
    def get_all(self, category: Optional[str] = None) -> Sequence["FaqResponseDTO"]: ...
    def get_categories(self) -> Sequence[str]: ...
    def update(self, faq_id: str, updates: dict[str, Any]) -> "FaqResponseDTO": ...
    def delete(self, faq_id: str) -> None: ...

@runtime_checkable
class SampleRepositoryProtocol(Protocol):
    def create(self, data: "SampleDTO") -> "SampleResponseDTO": ...
    def get_by_id(self, sample_id: str) -> "SampleResponseDTO": ...
    def get_by_slug(self, slug: str) -> "SampleResponseDTO": ...
    def get_featured(self) -> Sequence["SampleResponseDTO"]: ...
    def get_all(self) -> Sequence["SampleResponseDTO"]: ...
    def list_all(self, req: "SampleListRequestDTO") -> "SampleListResponseDTO": ...
    def update(self, sample_id: str, updates: dict[str, Any]) -> "SampleResponseDTO": ...
    def delete(self, sample_id: str) -> None: ...
    def get_samples_by_service_id(self, service_id: str) -> Sequence["SampleResponseDTO"]: ...

@runtime_checkable
class ServiceCategoryRepositoryProtocol(Protocol):
    def create(self, data: "ServiceCategoryDTO") -> "ServiceCategoryResponseDTO": ...
    def get_by_id(self, category_id: str) -> "ServiceCategoryResponseDTO": ...
    def get_all(self) -> Sequence["ServiceCategoryResponseDTO"]: ...
    def update(self, category_id: str, updates: dict[str, Any]) -> "ServiceCategoryResponseDTO": ...
    def delete(self, category_id: str) -> None: ...

@runtime_checkable
class ServiceRepositoryProtocol(Protocol):
    def create(self, data: "ServiceDTO") -> "ServiceResponseDTO": ...
    def get_by_id(self, service_id: str) -> "ServiceResponseDTO": ...
    def get_by_slug(self, slug: str) -> "ServiceResponseDTO": ...
    def get_all(self, active_only: bool = True) -> Sequence["ServiceResponseDTO"]: ...
    def get_featured(self) -> Sequence["ServiceResponseDTO"]: ...
    def update(self, service_id: str, updates: dict[str, Any]) -> "ServiceResponseDTO": ...
    def delete(self, service_id: str) -> None: ...
    def get_services_by_category(self, category_id: str) -> Sequence["ServiceResponseDTO"]: ...
    def get_service_mix(self, client_id: str) -> Sequence[tuple[str, int]]: ...

@runtime_checkable
class TestimonialRepositoryProtocol(Protocol):
    def create(self, data: "TestimonialDTO") -> "TestimonialResponseDTO": ...
    def get_by_id(self, testimonial_id: str) -> "TestimonialResponseDTO": ...
    def get_approved(self, service_id: Optional[str] = None) -> Sequence["TestimonialResponseDTO"]: ...
    def get_pending(self) -> Sequence["TestimonialResponseDTO"]: ...
    def approve(self, testimonial_id: str) -> "TestimonialResponseDTO": ...
    def update(self, testimonial_id: str, updates: dict[str, Any]) -> "TestimonialResponseDTO": ...
    def delete(self, testimonial_id: str) -> None: ...

@runtime_checkable
class PricingCategoryRepositoryProtocol(Protocol):
    def create(self, data: "PricingCategoryDTO") -> "PricingCategoryResponseDTO": ...
    def get_by_id(self, category_id: str) -> "PricingCategoryResponseDTO": ...
    def get_all(self) -> Sequence["PricingCategoryResponseDTO"]: ...
    def update(self, category_id: str, updates: dict[str, Any]) -> "PricingCategoryResponseDTO": ...
    def delete(self, category_id: str) -> None: ...

@runtime_checkable
class PriceRateRepositoryProtocol(Protocol):
    def create(self, data: "PriceRateDTO") -> "PriceRateResponseDTO": ...
    def get_by_id(self, rate_id: str) -> "PriceRateResponseDTO": ...
    def get_by_dimensions(self, lookup: "PriceRateLookupDTO") -> "PriceRateResponseDTO": ...
    def get_by_category(self, pricing_category_id: str, active_only: bool = True) -> Sequence["PriceRateResponseDTO"]: ...
    def update(self, rate_id: str, updates: dict[str, Any]) -> "PriceRateResponseDTO": ...
    def delete(self, rate_id: str) -> None: ...

@runtime_checkable
class ActivityLogRepositoryProtocol(Protocol):
    def create(self, data: "ActivityLogCreateDTO") -> "ActivityLogResponseDTO": ...
    def get_by_id(self, log_id: str) -> "ActivityLogResponseDTO": ...
    def get_filtered(self, filters: "ActivityLogFilterDTO") -> tuple[Sequence["ActivityLogResponseDTO"], int]: ...

@runtime_checkable
class EmailLogRepositoryProtocol(Protocol):
    def create(self, data: "EmailLogCreateDTO") -> "EmailLogResponseDTO": ...
    def get_by_id(self, log_id: str) -> "EmailLogResponseDTO": ...
    def get_filtered(self, filters: "EmailLogFilterDTO") -> tuple[Sequence["EmailLogResponseDTO"], int]: ...
    def update_status(self, log_id: str, data: "EmailLogUpdateDTO") -> "EmailLogResponseDTO": ...

@runtime_checkable
class OrderStatusHistoryRepositoryProtocol(Protocol):
    def create(self, data: "OrderStatusHistoryCreateDTO") -> "OrderStatusHistoryResponseDTO": ...
    def get_by_id(self, history_id: str) -> "OrderStatusHistoryResponseDTO": ...
    def get_by_order(self, order_id: str, page: int = 1, per_page: int = 20) -> tuple[Sequence["OrderStatusHistoryResponseDTO"], int]: ...

@runtime_checkable
class PriceHistoryRepositoryProtocol(Protocol):
    def create(self, data: "PriceHistoryCreateDTO") -> "PriceHistoryResponseDTO": ...
    def get_by_id(self, history_id: str) -> "PriceHistoryResponseDTO": ...
    def get_by_rate(self, rate_id: str, page: int = 1, per_page: int = 20) -> tuple[Sequence["PriceHistoryResponseDTO"], int]: ...

@runtime_checkable
class OrderRepositoryProtocol(Protocol):
    def get_active_orders(self, client_id: str) -> Sequence["Order"]: ...
    def get_paid_order_count(self, client_id: str) -> int: ...
    def get_latest_active_order(self, client_id: str) -> Optional["Order"]: ...
    def get_upcoming_deadlines(self, client_id: str, limit: int = 3) -> Sequence["Order"]: ...
    def get_project_lifecycle(self, client_id: str) -> Sequence[tuple[str, int]]: ...
    def get_order_for_reorder(self, order_id: str, client_id: str) -> "Order": ...
    def create_reorder(self, source: "Order", client_id: str) -> "Order": ...

@runtime_checkable
class PaymentsManagerProtocol(Protocol):
    def create(self, data: "PaymentCreateDTO") -> "PaymentResponseDTO": ...
    def get_by_id(self, payment_id: str) -> "PaymentResponseDTO": ...
    def get_by_order_id(self, order_id: str) -> list["PaymentResponseDTO"]: ...
    def update(self, payment_id: str, data: "PaymentUpdateDTO") -> "PaymentResponseDTO": ...
    def get_spending_velocity(self, client_id: str, months: int = 6) -> list[tuple[str, float]]: ...

@runtime_checkable
class InvoiceManagerProtocol(Protocol):
    def create(self, data: "InvoiceCreateDTO") -> "InvoiceResponseDTO": ...
    def get_by_id(self, invoice_id: str) -> "InvoiceResponseDTO": ...
    def get_by_number(self, invoice_number: str) -> "InvoiceResponseDTO": ...
    def update(self, invoice_id: str, data: "InvoiceUpdateDTO") -> "InvoiceResponseDTO": ...

@runtime_checkable
class TransactionManagerProtocol(Protocol):
    def create(self, data: "TransactionCreateDTO") -> "TransactionResponseDTO": ...
    def get_by_id(self, transaction_id: str) -> "TransactionResponseDTO": ...
    def get_by_payment_id(self, payment_id: str) -> list["TransactionResponseDTO"]: ...

@runtime_checkable
class DiscountManagerProtocol(Protocol):
    def create(self, data: "DiscountCreateDTO") -> "DiscountResponseDTO": ...
    def get_by_id(self, discount_id: str) -> "DiscountResponseDTO": ...
    def get_by_code(self, code: str) -> "DiscountResponseDTO": ...
    def update(self, discount_id: str, data: "DiscountUpdateDTO") -> "DiscountResponseDTO": ...
    def increment_usage(self, discount_id: str) -> "DiscountResponseDTO": ...

@runtime_checkable
class RefundManagerProtocol(Protocol):
    def create(self, data: "RefundCreateDTO") -> "RefundResponseDTO": ...
    def get_by_id(self, refund_id: str) -> "RefundResponseDTO": ...
    def update_status(self, refund_id: str, data: "RefundUpdateDTO") -> "RefundResponseDTO": ...

@runtime_checkable
class AcceptedMethodManagerProtocol(Protocol):
    def create(self, data: "AcceptedMethodCreateDTO") -> "AcceptedMethodResponseDTO": ...
    def update(self, method_id: str, data: "AcceptedMethodUpdateDTO") -> "AcceptedMethodResponseDTO": ...
    def get_by_id(self, method_id: str) -> "AcceptedMethodResponseDTO": ...
    def get_all_active(self) -> list["AcceptedMethodResponseDTO"]: ...

@runtime_checkable
class PaymentRepositoryProtocol(Protocol):
    @property
    def payment(self) -> PaymentsManagerProtocol: ...
    @property
    def invoice(self) -> InvoiceManagerProtocol: ...
    @property
    def transaction(self) -> TransactionManagerProtocol: ...
    @property
    def discount(self) -> DiscountManagerProtocol: ...
    @property
    def refund(self) -> RefundManagerProtocol: ...
    @property
    def accepted_method(self) -> AcceptedMethodManagerProtocol: ...

@runtime_checkable
class PreferenceRepositoryProtocol(Protocol):
    def get_all_preferences(self, user_id: str) -> "AllPreferencesResponseDTO": ...
    def update_category(self, category: str, user_id: str, data: dict[str, Any]) -> Any: ...
